"""Create final evidence summaries from generated quality reports."""

from __future__ import annotations

import json
from pathlib import Path
from typing import cast

EVIDENCE_DIR = Path("evidence")


def _read_json(name: str) -> dict[str, object]:
    path = EVIDENCE_DIR / name
    if not path.exists():
        return {"status": "not_executed", "reason": f"{name} not generated"}
    return cast(dict[str, object], json.loads(path.read_text(encoding="utf-8")))


def main() -> int:
    EVIDENCE_DIR.mkdir(exist_ok=True)
    evaluation = _read_json("rag-evaluation.json")
    security = _read_json("security-report.json")
    cost = _read_json("cost-report.json")
    loop = _read_json("loop-summary.json")
    verify = _read_json("verify-summary.json")
    report = f"""# Final Release Report

## Status

- Verification: {verify.get("status")}
- RAG evaluation: {evaluation.get("status")}
- Security report: {security.get("status")}
- Cost report: {cost.get("status")}
- Loop summary: {loop.get("status")}

## Evidence

Reports in this directory are generated by executable local scripts. A mandatory
gate that cannot run is marked as `not_executed` and causes verification to fail.
The software bill of materials is generated in CycloneDX JSON format by pip-audit.
"""
    (EVIDENCE_DIR / "final-release-report.md").write_text(report, encoding="utf-8")

    sbom_path = EVIDENCE_DIR / "software-bill-of-materials.json"
    if not sbom_path.exists():
        sbom_path.write_text(
            json.dumps(
                {
                    "status": "not_executed",
                    "reason": "CycloneDX SBOM gate has not run",
                },
                indent=2,
                sort_keys=True,
            )
            + "\n",
            encoding="utf-8",
        )

    threat_validation = """# Threat Model Validation

This file is generated from the current local evidence set. Test-to-control links
are documented in `docs/THREAT_MODEL.md`. Missing mandatory security tools make
`make verify` fail rather than being counted as a pass.
"""
    (EVIDENCE_DIR / "threat-model-validation.md").write_text(
        threat_validation,
        encoding="utf-8",
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
