"""Interactive Streamlit workspace for the RAGOps Enterprise Copilot."""

from __future__ import annotations

import json
import os
from collections.abc import Mapping
from html import escape
from typing import Any
from urllib.error import HTTPError, URLError
from urllib.request import Request, urlopen

import streamlit as st

API_BASE_URL = os.getenv("RAGOPS_API_URL", "http://localhost:8000").rstrip("/")

TENANTS = {
    "Atlas Industrial": "tenant-alpha",
    "Orion Health Systems": "tenant-beta",
    "UrbanGrid Services": "tenant-gamma",
}
ROLES = {
    "Vertrieb": "sales",
    "Kundenservice": "support",
    "Betrieb": "operations",
    "Compliance": "compliance",
    "Administration": "admin",
}
SUGGESTED_QUESTIONS = (
    (
        "Vertragsrisiken",
        "Welche Enterprise-Kunden haben offene kritische Supportfälle und einen Vertrag, "
        "der innerhalb der nächsten 60 Tage ausläuft? Welche Maßnahmen sollte der "
        "Vertrieb einleiten?",
    ),
    ("Preise", "Welche aktuellen Preisregeln gelten für Enterprise-Verträge?"),
    ("Compliance", "Welche Compliance-Richtlinien gelten für Kundendaten?"),
)


class DashboardApiError(RuntimeError):
    """A safe error raised when the dashboard cannot use the API."""


def api_request(
    method: str,
    path: str,
    payload: Mapping[str, object] | None = None,
    *,
    timeout: float = 20.0,
) -> Any:
    """Call the internal API without adding another HTTP client dependency."""
    body = json.dumps(payload).encode("utf-8") if payload is not None else None
    request = Request(  # noqa: S310 - configured internal HTTP endpoint
        f"{API_BASE_URL}{path}",
        data=body,
        headers={"Content-Type": "application/json", "Accept": "application/json"},
        method=method,
    )
    try:
        with urlopen(request, timeout=timeout) as response:  # noqa: S310 - fixed internal URL
            content = response.read().decode("utf-8")
            return json.loads(content) if content else None
    except HTTPError as exc:
        try:
            detail = json.loads(exc.read().decode("utf-8")).get("detail", "Anfrage fehlgeschlagen")
        except (json.JSONDecodeError, UnicodeDecodeError):
            detail = "Anfrage fehlgeschlagen"
        raise DashboardApiError(f"API-Anfrage fehlgeschlagen ({exc.code}): {detail}") from exc
    except (TimeoutError, URLError) as exc:
        raise DashboardApiError(
            "Die API ist derzeit nicht erreichbar. Bitte den Dienststatus prüfen."
        ) from exc


def api_text(path: str, *, timeout: float = 10.0) -> str:
    request = Request(  # noqa: S310 - configured internal HTTP endpoint
        f"{API_BASE_URL}{path}", method="GET"
    )
    try:
        with urlopen(request, timeout=timeout) as response:  # noqa: S310 - fixed internal URL
            decoded: str = response.read().decode("utf-8")
            return decoded
    except (HTTPError, TimeoutError, URLError) as exc:
        raise DashboardApiError("Der Metrik-Endpunkt ist derzeit nicht erreichbar.") from exc


def parse_prometheus(payload: str) -> dict[str, float]:
    """Parse the simple Prometheus exposition generated by this demo."""
    metrics: dict[str, float] = {}
    for line in payload.splitlines():
        if not line or line.startswith("#"):
            continue
        name, _, raw_value = line.partition(" ")
        if name.startswith("ragops_") and raw_value:
            try:
                metrics[name.removeprefix("ragops_")] = float(raw_value)
            except ValueError:
                continue
    return metrics


def numeric(value: object) -> float | None:
    if isinstance(value, int | float | str):
        try:
            return float(value)
        except ValueError:
            return None
    return None


def percent(value: object) -> str:
    number = numeric(value)
    return f"{number * 100:.0f}%" if number is not None else "--"


def milliseconds(value: object) -> str:
    number = numeric(value)
    return f"{number:.1f} ms" if number is not None else "--"


def option_label(options: Mapping[str, str], value: str) -> str:
    """Return the user-facing label for an internal option value."""
    return next((label for label, option in options.items() if option == value), value)


def chat_role(message: Mapping[str, object]) -> str:
    """Constrain chat roles to the two presentation roles supported by Streamlit."""
    return "user" if message.get("role") == "user" else "assistant"


def inject_styles() -> None:
    st.markdown(
        """
        <style>
        :root {
            --ink: #172033; --muted: #687386; --line: #e4e8ef;
            --surface: #ffffff; --canvas: #f4f6f9;
            --brand: #176b5b; --brand-soft: #e5f4ef;
        }
        [data-testid="stAppViewContainer"] { background: var(--canvas); }
        [data-testid="stHeader"] { background: transparent; }
        [data-testid="stMain"] .block-container {
            max-width: 1240px; padding-top: 2rem; padding-bottom: 5rem;
        }
        [data-testid="stSidebar"] {
            background: #141b25; border-right: 1px solid #202a38;
        }
        [data-testid="stSidebar"] * { color: #f7f9fc; }
        [data-testid="stSidebar"] [data-testid="stWidgetLabel"] p,
        [data-testid="stSidebar"] .stCaption { color: #aeb8c7 !important; }
        [data-testid="stSidebar"] [data-testid="stSelectbox"] input {
            color: #172033 !important;
            -webkit-text-fill-color: #172033 !important;
            opacity: 1 !important;
        }
        [data-testid="stSidebar"] [data-testid="stSelectbox"] button {
            color: #526071 !important;
        }
        [data-testid="stSidebar"] [data-testid="stButton"] button {
            background: #1c2634; border-color: #344154;
        }
        [data-testid="stSidebar"] [data-testid="stButton"] button * {
            color: #f7f9fc !important;
            -webkit-text-fill-color: #f7f9fc !important;
        }
        [data-testid="stSidebar"] [data-testid="stExpander"] {
            background: #1c2634; border-color: #344154;
        }
        [data-testid="stSidebar"] [data-testid="stExpander"] * {
            color: #f7f9fc;
        }
        [data-testid="stSidebar"] [role="radiogroup"] label {
            border-radius: 6px; padding: .45rem .6rem;
        }
        [data-testid="stSidebar"] [role="radiogroup"] label:has(input:checked) {
            background: #233043;
        }
        .brand-lockup { display: flex; gap: .75rem; align-items: center; margin: .4rem 0 2rem; }
        .brand-mark {
            width: 38px; height: 38px; display: grid; place-items: center;
            border-radius: 7px; background: #36a085; color: white; font-weight: 800;
        }
        .brand-name { color: #fff; font-size: 1.02rem; font-weight: 700; line-height: 1.15; }
        .brand-sub { color: #97a4b5; font-size: .72rem; margin-top: .2rem; }
        .page-kicker {
            color: var(--brand); font-size: .74rem; font-weight: 750;
            text-transform: uppercase;
        }
        .page-title {
            color: var(--ink); font-size: 1.75rem; font-weight: 760;
            margin: .15rem 0 .25rem;
        }
        .page-subtitle { color: var(--muted); font-size: .93rem; margin-bottom: 1.25rem; }
        .status-row { display: flex; align-items: center; gap: .55rem; }
        .status-dot { width: 8px; height: 8px; border-radius: 50%; background: #35b37e; }
        .status-label { color: #aeb8c7; font-size: .78rem; }
        .context-strip {
            display: flex; align-items: center; gap: .55rem; flex-wrap: wrap;
            border: 1px solid var(--line); background: var(--surface); border-radius: 7px;
            padding: .68rem .85rem; margin-bottom: 1.25rem;
        }
        .context-pill {
            background: #eef1f5; color: #445066; border-radius: 999px;
            padding: .26rem .58rem; font-size: .74rem; font-weight: 650;
        }
        .trust-pill { background: var(--brand-soft); color: #145e50; }
        [data-testid="stChatMessage"] {
            background: var(--surface); border: 1px solid var(--line);
            border-radius: 7px; padding: .45rem .7rem; margin-bottom: .7rem;
        }
        [data-testid="stChatMessage"] p { color: var(--ink); }
        [data-testid="stChatInput"] { border-color: #cbd2dc; }
        [data-testid="stMetric"] {
            background: var(--surface); border: 1px solid var(--line);
            border-radius: 7px; padding: .85rem 1rem;
        }
        [data-testid="stMetricLabel"] { color: var(--muted); }
        [data-testid="stMetricValue"] { color: var(--ink); }
        [data-testid="stButton"] button {
            min-height: 2.45rem; border-radius: 6px; border-color: #cfd6df; font-weight: 620;
        }
        [data-testid="stButton"] button[kind="primary"] {
            background: var(--brand); border-color: var(--brand); color: #fff;
        }
        [data-testid="stExpander"] {
            background: var(--surface); border: 1px solid var(--line); border-radius: 7px;
        }
        .source-row { border-left: 3px solid var(--brand); padding: .1rem 0 .1rem .75rem; }
        .source-title { color: var(--ink); font-size: .88rem; font-weight: 700; }
        .source-meta { color: var(--muted); font-size: .74rem; margin-top: .15rem; }
        .empty-state {
            background: var(--surface); border: 1px dashed #c8d0dc; border-radius: 7px;
            padding: 2rem; text-align: center; color: var(--muted);
        }
        .guard-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: .7rem; }
        .guard-item {
            background: var(--surface); border: 1px solid var(--line);
            border-radius: 7px; padding: .85rem;
        }
        .guard-title { color: var(--ink); font-weight: 700; font-size: .84rem; }
        .guard-state { color: var(--brand); font-size: .75rem; margin-top: .3rem; }
        hr { border-color: var(--line) !important; }
        @media (max-width: 760px) {
            [data-testid="stMain"] .block-container { padding: 1rem .8rem 4.5rem; }
            .page-title { font-size: 1.45rem; }
            .guard-grid { grid-template-columns: 1fr; }
        }
        </style>
        """,
        unsafe_allow_html=True,
    )


def render_page_header(kicker: str, title: str, subtitle: str) -> None:
    st.markdown(
        f"""
        <div class="page-kicker">{kicker}</div>
        <div class="page-title">{title}</div>
        <div class="page-subtitle">{subtitle}</div>
        """,
        unsafe_allow_html=True,
    )


def render_sidebar() -> tuple[str, str, int, str]:
    with st.sidebar:
        st.markdown(
            """
            <div class="brand-lockup">
              <div class="brand-mark">R</div>
              <div>
                <div class="brand-name">RAGOps</div>
                <div class="brand-sub">Enterprise Copilot</div>
              </div>
            </div>
            """,
            unsafe_allow_html=True,
        )
        navigation = st.radio(
            "Arbeitsbereich",
            ("Copilot", "Wissensbasis", "Monitoring", "Governance & Audit"),
            label_visibility="collapsed",
        )
        if st.button("Neue Unterhaltung", icon=":material/add_comment:", use_container_width=True):
            st.session_state.pop("messages", None)
            st.rerun()
        st.divider()
        tenant_label = st.selectbox("Mandant", tuple(TENANTS))
        role_label = st.selectbox("Rolle", tuple(ROLES))
        with st.expander("Retrieval-Einstellungen"):
            top_k = st.slider("Maximale Quellen", min_value=2, max_value=10, value=5)
        st.write("")
        try:
            ready = api_request("GET", "/ready", timeout=2.0)
            count = ready.get("documents", 0) if isinstance(ready, dict) else 0
            st.markdown(
                f'<div class="status-row"><span class="status-dot"></span>'
                f'<span class="status-label">API betriebsbereit · {count} '
                "Textabschnitte verfügbar</span></div>",
                unsafe_allow_html=True,
            )
        except DashboardApiError:
            st.error("API nicht erreichbar")
    return TENANTS[tenant_label], ROLES[role_label], top_k, navigation


def initialize_chat() -> None:
    if "messages" not in st.session_state:
        st.session_state.messages = [
            {
                "role": "assistant",
                "answer": (
                    "Guten Tag. Ich beantworte Fragen zu Kunden, Verträgen, Supportfällen "
                    "und Richtlinien. Jede Faktenantwort wird mit freigegebenen Quellen belegt."
                ),
                "citations": [],
                "metrics": {},
                "evidence_score": 0.0,
                "abstained": False,
            }
        ]


def render_citations(citations: list[dict[str, object]]) -> None:
    if not citations:
        return
    with st.expander(f"Quellen · {len(citations)}", expanded=False):
        for citation in citations:
            title = escape(str(citation.get("title", "Quelle ohne Titel")))
            source_id = escape(str(citation.get("source_id", "")))
            st.markdown(
                f"""
                <div class="source-row">
                  <div class="source-title">{title}</div>
                  <div class="source-meta">{source_id} ·
                  Relevanz {percent(citation.get("score", 0))}</div>
                </div>
                """,
                unsafe_allow_html=True,
            )
            st.write("")


def render_chat_message(message: dict[str, object]) -> None:
    role = chat_role(message)
    with st.chat_message(role):
        if role == "user":
            st.markdown(str(message.get("content", "")))
            return
        if message.get("abstained"):
            st.warning(str(message.get("answer", "")), icon=":material/gpp_bad:")
        else:
            st.markdown(str(message.get("answer", "")))
        citations = message.get("citations", [])
        if isinstance(citations, list):
            render_citations(citations)
        metrics = message.get("metrics", {})
        if isinstance(metrics, dict) and metrics:
            injection = (
                " · Prompt Injection blockiert" if metrics.get("prompt_injection_detected") else ""
            )
            st.caption(
                f"Evidenz {percent(message.get('evidence_score'))} · "
                f"Retrieval {milliseconds(metrics.get('retrieval_latency_ms'))} · "
                f"LLM {milliseconds(metrics.get('llm_latency_ms'))} · "
                f"{metrics.get('tokens', 0)} Token{injection}"
            )


def submit_question(question: str, tenant_id: str, role: str, top_k: int) -> None:
    question = question.strip()
    if not question:
        return
    st.session_state.messages.append({"role": "user", "content": question})
    try:
        response = api_request(
            "POST",
            "/v1/query",
            {
                "question": question,
                "tenant_id": tenant_id,
                "user_id": "portfolio-user",
                "role": role,
                "top_k": top_k,
            },
        )
        if not isinstance(response, dict):
            raise DashboardApiError("Die API hat eine ungültige Antwort geliefert.")
        st.session_state.messages.append({"role": "assistant", **response})
    except DashboardApiError as exc:
        st.session_state.messages.append(
            {
                "role": "assistant",
                "answer": str(exc),
                "citations": [],
                "metrics": {},
                "evidence_score": 0.0,
                "abstained": True,
            }
        )


def render_copilot(tenant_id: str, role: str, top_k: int) -> None:
    render_page_header(
        "Sicherer KI-Arbeitsbereich",
        "Enterprise Copilot",
        "Belegte Antworten aus kontrolliertem Wissen und synthetischen CRM-Daten.",
    )
    tenant_label = escape(option_label(TENANTS, tenant_id))
    role_label = escape(option_label(ROLES, role))
    st.markdown(
        f"""
        <div class="context-strip">
          <span class="context-pill">{tenant_label}</span>
          <span class="context-pill">{role_label}</span>
          <span class="context-pill trust-pill">Mandantenschutz aktiv</span>
          <span class="context-pill trust-pill">Quellenpflicht aktiv</span>
        </div>
        """,
        unsafe_allow_html=True,
    )
    initialize_chat()
    if len(st.session_state.messages) == 1:
        columns = st.columns(3)
        for column, (label, suggested_question) in zip(columns, SUGGESTED_QUESTIONS, strict=True):
            if column.button(label, use_container_width=True):
                submit_question(suggested_question, tenant_id, role, top_k)
                st.rerun()
    for message in st.session_state.messages:
        render_chat_message(message)
    prompt = st.chat_input("Frage zu Kunden, Verträgen, Supportfällen oder Richtlinien")
    if prompt:
        submit_question(prompt, tenant_id, role, top_k)
        st.rerun()


def render_knowledge_base(tenant_id: str) -> None:
    render_page_header(
        "Wissensbetrieb",
        "Wissensbasis",
        "Versionierte und klassifizierte Quellen des aktiven Mandanten.",
    )
    try:
        documents = api_request("GET", "/v1/documents")
    except DashboardApiError as exc:
        st.error(str(exc))
        return
    tenant_documents = [
        document
        for document in documents
        if isinstance(document, dict) and document.get("tenant_id") == tenant_id
    ]
    cols = st.columns(3)
    cols[0].metric("Verfügbare Dokumente", len(tenant_documents))
    cols[1].metric("Aktiver Mandant", option_label(TENANTS, tenant_id))
    versions = {str(document.get("version")) for document in tenant_documents}
    cols[2].metric("Enthaltene Versionen", len(versions))
    st.write("")
    action, _ = st.columns([1, 4])
    if action.button("Index aktualisieren", type="primary", use_container_width=True):
        with st.spinner("Kontrollierter Index wird aktualisiert..."):
            result = api_request("POST", "/v1/documents/ingest")
        st.success(f"Index bereit · {result.get('chunks', 0)} Textabschnitte")
    if tenant_documents:
        st.dataframe(
            tenant_documents,
            column_order=("title", "version", "access_level", "document_id"),
            column_config={
                "title": "Dokument",
                "version": "Version",
                "access_level": "Zugriff",
                "document_id": "Dokument-ID",
            },
            hide_index=True,
            use_container_width=True,
        )
    else:
        st.markdown(
            '<div class="empty-state">Für diesen Mandanten sind keine Dokumente verfügbar.</div>',
            unsafe_allow_html=True,
        )


def render_observability() -> None:
    render_page_header(
        "RAG-Betrieb",
        "Monitoring",
        "Live-Telemetrie und gemessene Retrieval-Qualität.",
    )
    try:
        live = parse_prometheus(api_text("/metrics"))
        costs = api_request("GET", "/v1/costs/summary")
        evaluation = api_request("GET", "/v1/evaluations")
    except DashboardApiError as exc:
        st.error(str(exc))
        return
    cols = st.columns(4)
    cols[0].metric("Anfragen", int(live.get("request_count", 0)))
    cols[1].metric("Erfolgsquote", percent(live.get("success_rate", 0)))
    cols[2].metric("Mittlere Latenz", milliseconds(live.get("avg_latency_ms", 0)))
    cols[3].metric("Geschätzte Kosten", f"EUR {float(costs.get('total_cost_eur', 0)):.4f}")
    st.write("")
    left, right = st.columns([1.35, 1])
    with left:
        st.subheader("Retrieval-Qualität")
        if evaluation.get("status") == "available":
            quality = [
                {
                    "Metrik": "Retrieval Hit Rate",
                    "Wert": float(evaluation.get("retrieval_hit_rate", 0)),
                },
                {"Metrik": "Recall@5", "Wert": float(evaluation.get("recall_at_5", 0))},
                {"Metrik": "Precision@5", "Wert": float(evaluation.get("precision_at_5", 0))},
                {
                    "Metrik": "Quellenabdeckung",
                    "Wert": float(evaluation.get("citation_coverage", 0)),
                },
                {
                    "Metrik": "Security-Testquote",
                    "Wert": float(evaluation.get("security_test_pass_rate", 0)),
                },
            ]
            st.bar_chart(quality, x="Metrik", y="Wert", horizontal=True, height=270)
        else:
            st.markdown(
                '<div class="empty-state">Es liegt noch keine Evaluation vor.</div>',
                unsafe_allow_html=True,
            )
    with right:
        st.subheader("Laufzeitsignale")
        signal_rows = {
            "Retrieval-Latenz": milliseconds(live.get("avg_retrieval_latency_ms", 0)),
            "LLM-Latenz": milliseconds(live.get("avg_llm_latency_ms", 0)),
            "Token": f"{int(live.get('total_tokens', 0)):,}",
            "Quellenabdeckung": percent(live.get("avg_citation_coverage", 0)),
        }
        for label, value in signal_rows.items():
            st.markdown(f"**{label}**")
            st.caption(value)
            st.divider()
    if evaluation.get("status") == "available":
        case_count = int(evaluation.get("case_count", 0))
        cost_per_request = (
            float(evaluation.get("total_cost_eur", 0)) / case_count if case_count else 0.0
        )
        st.subheader("Evaluationsziele")
        targets = st.columns(4)
        targets[0].metric("Gold-Testfälle", case_count)
        targets[1].metric("Mandantenlecks", int(evaluation.get("tenant_leakage_count", 0)))
        targets[2].metric("Ablehnungsquote", percent(evaluation.get("abstention_rate", 0)))
        targets[3].metric("Kosten / Anfrage", f"EUR {cost_per_request:.4f}")


def render_governance() -> None:
    render_page_header(
        "Vertrauenszentrum",
        "Governance & Audit",
        "Aktive Kontrollen und revisionsfähige Anfragenachweise.",
    )
    try:
        live = parse_prometheus(api_text("/metrics"))
        events = api_request("GET", "/v1/audit-events")
    except DashboardApiError as exc:
        st.error(str(exc))
        return
    st.markdown(
        """
        <div class="guard-grid">
          <div class="guard-item">
            <div class="guard-title">Mandantentrennung</div>
            <div class="guard-state">Aktiv · Retrieval begrenzt</div>
          </div>
          <div class="guard-item">
            <div class="guard-title">Quellenvalidierung</div>
            <div class="guard-state">Aktiv · Ablehnung bei Fehlern</div>
          </div>
          <div class="guard-item">
            <div class="guard-title">PII-Maskierung</div>
            <div class="guard-state">Aktiv · Antwortfilter</div>
          </div>
          <div class="guard-item">
            <div class="guard-title">Prompt Injection</div>
            <div class="guard-state">Aktiv · Eingabe- und Dokumentprüfung</div>
          </div>
          <div class="guard-item">
            <div class="guard-title">RBAC</div>
            <div class="guard-state">Aktiv · rollengebundener Zugriff</div>
          </div>
          <div class="guard-item">
            <div class="guard-title">Audit-Protokollierung</div>
            <div class="guard-state">Aktiv · Korrelations-IDs</div>
          </div>
        </div>
        """,
        unsafe_allow_html=True,
    )
    st.write("")
    cols = st.columns(3)
    cols[0].metric("Erkannte Prompt-Injections", int(live.get("prompt_injection_detections", 0)))
    cols[1].metric("Blockierte Zugriffe", int(live.get("blocked_access_attempts", 0)))
    cols[2].metric("Audit-Ereignisse", len(events) if isinstance(events, list) else 0)
    st.write("")
    st.subheader("Letzte Audit-Ereignisse")
    if isinstance(events, list) and events:
        st.dataframe(
            list(reversed(events)),
            hide_index=True,
            use_container_width=True,
            column_order=(
                "timestamp",
                "event_type",
                "tenant_id",
                "user_id",
                "outcome",
                "correlation_id",
            ),
            column_config={
                "timestamp": "Zeitpunkt",
                "event_type": "Ereignistyp",
                "tenant_id": "Mandant",
                "user_id": "Benutzer-ID",
                "outcome": "Ergebnis",
                "correlation_id": "Korrelations-ID",
            },
        )
    else:
        st.markdown(
            '<div class="empty-state">In dieser Laufzeit wurden keine '
            "Audit-Ereignisse erfasst.</div>",
            unsafe_allow_html=True,
        )


def main() -> None:
    st.set_page_config(
        page_title="RAGOps Enterprise Copilot",
        page_icon=":material/shield_person:",
        layout="wide",
        initial_sidebar_state="expanded",
    )
    inject_styles()
    tenant_id, role, top_k, navigation = render_sidebar()
    if navigation == "Copilot":
        render_copilot(tenant_id, role, top_k)
    elif navigation == "Wissensbasis":
        render_knowledge_base(tenant_id)
    elif navigation == "Monitoring":
        render_observability()
    else:
        render_governance()


if __name__ == "__main__":
    main()
